### ISSUE TITLE
G2 (space between 2 functions )not handled + C1 fucked up

### ISSUE THREAD

**Issue by izimio** [Just1truc/Abricot-Norminette#1]
G2 error 
C1 bad handled 
viens me voir je te montre

**Comment by leodubosclard** [comment]
Oui c'est vrai j'ai eu les mêmes erreurs, dommage...

**Comment by leodubosclard** [comment]
à quand la correction de l'issue ?

**Comment by leodubosclard** [comment]
@Just1truc

**Comment by Just1truc** [comment]
Hello,

Thanks to your report, this issue has been handled easily. I advise you to report any problem in order to perform the error detection ability.

Best regards, Justin.
