### ISSUE TITLE
J'ai une mineure dans mon stumper à cause de ça

### ISSUE THREAD

**Issue by JBobi** [Just1truc/Abricot-Norminette#2]
j'ai eu une erreur L4 dans mon stumper sur un return

abricot ne trouve pas l'erreur sur la ligne : return(value)

Il faut en effet laisser un espace entre le return et la valeur retournée.

Merci de réparer cette erreur au plus vite c'est inadmissible

**Comment by leodubosclard** [comment]
J'ai eu le même problème mais pas sur mon stumper par contre rip.

REMBOURSEZ !!

**Comment by Just1truc** [comment]
Hello,

Sorry to here that my incompetence made you fail. I hope you'll be able to calm your anger seeing that this problem has been handled thanks to you.Also, I advise you to report any problem in order to perform the error detection ability.

Best regards, Justin.

**Comment by Just1truc** [comment]
Hello,

Sorry to here that my incompetence made you fail. I hope you'll be able to calm your anger seeing that this problem has been handled thanks to you.Also, I advise you to report any problem in order to perform the error detection ability.

Best regards, Justin.
