### ISSUE TITLE
03 - inline static struct added in the function total number

### ISSUE THREAD

**Issue by davd-gzl** [Just1truc/Abricot-Norminette#21]
This inline structure in a .c file count as 3 functions

```C
static const struct flag_s {
    size_t value;
    char key[32];
} FLAGS[] = {{BFD_NO_FLAGS, "BFD_NO_FLAGS"}, {HAS_RELOC, "HAS_RELOC"},
{EXEC_P, "EXEC_P"}, {HAS_LINENO, "HAS_LINENO"}, {HAS_DEBUG, "HAS_DEBUG"},
{HAS_SYMS, "HAS_SYMS"}, {HAS_LOCALS, "HAS_LOCALS"}, {DYNAMIC, "DYNAMIC"},
{WP_TEXT, "WP_TEXT"}, {D_PAGED, "D_PAGED"}};
```

**Comment by Fyroeo** [comment]
Hi David,
I'm Thomas, quality checker for Abricot-Norminette.

Thanks for your issue. With your help, Abricot will become better and better.

I would need more details about the issue you reported : 
- Are you using the last version ? You might check if there is an update available using the `abricot --update` command.
- Can you tell me which of the following is the correct issue : Your example should be counted as 3 functions by Abricot OR Abricot is counting your example as 3 functions whereas it should only be one ?

Thanks for your reply :)

**Comment by MathiDEV** [comment]
Hi David,
I'm Mathias, active contributor of Abricot-Norminette.

Thanks for your issue. With your help, Abricot will become better and better.

I'm sorry but your code is awful.

Have a nice day !

**Comment by davd-gzl** [comment]
Hello,
I'm using the last version of abricot

What I sent should not be counted as a function, but it's counted because it takes the first character equal to { as a function
https://github.com/Just1truc/Abricot-Norminette/blob/main/brico.py#L185

I'll do a pull request later today

**Comment by Fyroeo** [comment]
Hi David,
Thanks for you reply.

I was able to reproduce the bug using the last version of Abricot with the following test file:
```c
/*
** EPITECH PROJECT, 2022
** random
** File description:
** test
*/

static const struct flag_s {
    size_t value;
    char key[32];
} FLAGS[] = {{BFD_NO_FLAGS, "BFD_NO_FLAGS"}, {HAS_RELOC, "HAS_RELOC"},
{EXEC_P, "EXEC_P"}, {HAS_LINENO, "HAS_LINENO"}, {HAS_DEBUG, "HAS_DEBUG"},
{HAS_SYMS, "HAS_SYMS"}, {HAS_LOCALS, "HAS_LOCALS"}, {DYNAMIC, "DYNAMIC"},
{WP_TEXT, "WP_TEXT"}, {D_PAGED, "D_PAGED"}};

static const struct flag_s {
    size_t value;
    char key[32];
} FLAGS[] = {{BFD_NO_FLAGS, "BFD_NO_FLAGS"}, {HAS_RELOC, "HAS_RELOC"},
{EXEC_P, "EXEC_P"}, {HAS_LINENO, "HAS_LINENO"}, {HAS_DEBUG, "HAS_DEBUG"},
{HAS_SYMS, "HAS_SYMS"}, {HAS_LOCALS, "HAS_LOCALS"}, {DYNAMIC, "DYNAMIC"},
{WP_TEXT, "WP_TEXT"}, {D_PAGED, "D_PAGED"}};
```

The output of Abricot was:
```
‣ In File test.c
  [MAJOR] (O3) - Too many functions in one file (6 > 5). (test.c)
  [MINOR] (G2) - There should be only one empty_line each time. (test.c:22)
  [MINOR] (G2) - There should be only one empty_line each time. (test.c:22)
```

Therefore, I'm marking this issue as a bug, and it will be corrected in the near future.
Feel free to make a pull request if you know how to fix it ! :)

**Comment by Just1truc** [comment]
Hi David,

Thank you very much for your report. Thanks to you, abricot is becoming more reliable.
Do not hesitate to report other problem when you encounter some.

Have a Nice Day :)
