### ISSUE TITLE
[BUG]: L4 (Misplaced curly brackets) error

### ISSUE THREAD

**Issue by leodubosclard** [Just1truc/Abricot-Norminette#30]
### What happened?

Bonjour,

Je me permets d'écrire cette issue suite à un bug rencontré lors de mon utilisation de Abricot-Norminette.

En effet, lors d'une déclaration d'un tableau structure. Abricot-Norminette ma alors trigger une L4 pour rien.

Pas cool, je ne recommande pas.

Cordialement,

Preuves:
![image](https://user-images.githubusercontent.com/47077683/158582358-2dedc82a-d2ca-43fa-a949-1bbbc025a0fe.png)

### Version

Yes

### What OS are you seeing the problem on?

Fedora based

### Relevant output

```shell
[MINOR] (L4) - Curly brackets misplaced. (src/options.c:65)
![image](https://user-images.githubusercontent.com/47077683/158582358-2dedc82a-d2ca-43fa-a949-1bbbc025a0fe.png)
```

**Comment by Fyroeo** [comment]
Hi Léo,
I tested your issue and was able to reproduce it using the latest version.

The issue only happen if the example provided by Léo is inside a function. Outside a function, Abricot doesn't trigger a coding-style error.

Therefore, I'm marking this issue as validated, and I'm assigning one of the maintainers to repair it.

Thanks for your report !

**Comment by Just1truc** [comment]
T_T

**Comment by Just1truc** [comment]
Hi,

Thanks to you, this problem has been fixed really fastest avoiding abricot to report unnecessary errors to the user.
Please continue to use abricot and report any bug you find in order to improve the Norminette to make it one of the best of it's kind.

Cordially,
