### ISSUE TITLE
[BUG]: No trigger coding style error (if)

### ISSUE THREAD

**Issue by leodubosclard** [Just1truc/Abricot-Norminette#31]
### What happened?

Bonjour,

Je me permets d'écrire cette issue car, en utilisant Abricot-Norminette. J'ai vu qu'elle ne détecte pas une erreur de coding style.

Bien cordialement,

Preuves:
![image](https://user-images.githubusercontent.com/47077683/158593591-4bb07711-a410-450d-bbb1-304bafc34af1.png)
![image](https://user-images.githubusercontent.com/47077683/158593962-8d046155-8e19-46bb-b8c2-0021a0f5754c.png)

### Version

Yes

### What OS are you seeing the problem on?

Fedora based

### Relevant output

```shell
No Coding style error detected : Code clean
```

**Comment by Fyroeo** [comment]
Hi Léo,
I tested your issue and was able to reproduce it using the latest version.

Therefore, I'm marking this issue as validated, and I'm assigning one of the maintainers to repair it.

Thanks for your report !

**Comment by Just1truc** [comment]
hi,

Thank you for reporting this error. It's now triggered as it should.

Cordially,
