### ISSUE TITLE
[BUG]: You can ignore Jenkins files

### ISSUE THREAD

**Issue by MathiDEV** [Just1truc/Abricot-Norminette#33]
### What happened?

![image](https://user-images.githubusercontent.com/40570499/158896232-37969d80-3f1d-4e5d-b13c-69cb3a1b0c38.png)

Epitech's norminette doesn't report "**/Jenkinsfile" so you can ignore it !

### Version

Yes

### What OS are you seeing the problem on?

Debian based

**Comment by Fyroeo** [comment]
Hello @MathiDEV,
I don't understand your issue as Abricot is already not reporting the Jenkinsfile, neither do the moulinette.
May you precise what is the issue ?

Thanks

**Comment by Fyroeo** [comment]
Never mind, found out that it is being reported as an O4 whereas I thought it will be reported as an O1.

Therefore, I'm marking this issue as verified and I assign one of the maintainers.

Thanks for your report :)

**Comment by Just1truc** [comment]
Hi,

I know Epitech's nominette doesn't report Jenkinsfiles. However, it is clearly marked in the coding style that it should.
![image](https://user-images.githubusercontent.com/68695857/158907435-ee21757b-67a6-4e5a-9f91-b024152f5646.png)

Have a good day.
