### ISSUE TITLE
[REQUEST]: Handling F2 and V1

### ISSUE THREAD

**Issue by MathiDEV** [Just1truc/Abricot-Norminette#35]
### What would you like to be added ?

With 2 regex you can do it easily

### Version

Yes

### Did you check your request is not already asked ?

Yes

**Comment by Just1truc** [comment]
hi,

i completely understand why you would say that for v1 errors. However, correct f2 errors aren't that easy to detect. In order to accomplish it, i would need a database of all english verbs and abricot is meant to be light.

Yours sincerely.

**Comment by Fyroeo** [comment]
@Just1truc maybe we can make Abricot to check with a distant server so it doesn't contain any database.
But there is some limitations:
- What if the user is not connected to the internet ?
- What about privacy compliance ?
- Wouldn't it be a security risk for the user if the distant server has been hacked and Abricot is parsing the hacker output ?

If we opt for this, I think we should manage the server by ourselves so we are 100% in control.

What do you think ?

**Comment by Just1truc** [comment]
Hi,

I think it would be too troublesome to be impleted correctly.
Consequently, i've decided that we would implement a simple version of this error and V1.

Yours sincerely
