### ISSUE TITLE
[BUG]: H2

### ISSUE THREAD

**Issue by leodubosclard** [Just1truc/Abricot-Norminette#36]
### What happened?

Pourquoi la mouli me trigger une H2 mais pas Abricot ?

sus.

### Version

Yes

### What OS are you seeing the problem on?

Debian based, Fedora based, macOS, Windows, Other

### Relevant output

```shell
bite
```

**Comment by Just1truc** [comment]
hi,

I can't work on this issue if there is no proof to explain the problem.

Please retry another time with visual proof.
