### ISSUE TITLE
[BUG]: H2 - Pragma once not handled

### ISSUE THREAD

**Issue by davd-gzl** [Just1truc/Abricot-Norminette#39]
### What happened?

I'm getting an error from an header not being protected from double inclusions while it is using #pragma once

### Version

Yes

### What OS are you seeing the problem on?

Debian based

### Relevant output

```shell
/*
** EPITECH PROJECT, 2021
** strace
** File description:
** syscalls table
*/

#pragma once

    #include "strace.h"
    #include <stdlib.h>
```

**Comment by Just1truc** [comment]
keskecékesa

**Comment by Just1truc** [comment]
Hi,

This problem has been handled thanks to your report, feel free to report more in the future if you need to.

Have a nice day
