### ISSUE TITLE
[BUG]: F5 - Macro function definition count as real function

### ISSUE THREAD

**Issue by davd-gzl** [Just1truc/Abricot-Norminette#40]
### What happened?

When using a macro on a function definition, it's counted as a real function, and await parameters type. Here it wait for a void parameter

### Version

Yes

### What OS are you seeing the problem on?

Debian based

### Relevant output

```shell
void s_global(void)
{
    puts("Hello world !");
}
#define g_exit_status s_global() // Trigger F5
```

**Comment by Just1truc** [comment]
part don?
dafuk

**Comment by Just1truc** [comment]
Hi,

Thanks for your report. I've realised that i shouldn't count functions in header files anyway.

Have a nice day.
