### ISSUE TITLE
[BUG]: G4 inexistant detected

### ISSUE THREAD

**Issue by Allan00z** [Just1truc/Abricot-Norminette#43]
### What happened?

Une erreur G4 a été detectée dans mon programme mais elle se trouve dans le "sys/stat.h". Voici quelques screens ! 
![image](https://user-images.githubusercontent.com/91593239/160577326-1041f5c8-1168-436c-8d14-1704cb9d4b56.png)

![image](https://user-images.githubusercontent.com/91593239/160577467-56f5edec-05ba-4f0d-abf3-50e83b4f4f30.png)

### Version

Yes

### What OS are you seeing the problem on?

Fedora based

**Comment by Just1truc** [comment]
Hi,

Thanks for your report. Your error has been fixed

Have a nice day
