### ISSUE TITLE
[BUG]: L6 & L5 & L6 & G2

### ISSUE THREAD

**Issue by izimio** [Just1truc/Abricot-Norminette#44]
### What happened?

char **get_standard(void)
{   <== L6 ? 
    int i = -1;
    char **res = NULL;
    int st = 0;
    int end = 0;
    file_t *file = fourmilliere();
                                              <=== L5 ?                  
    res = malloc(sizeof(char *) * (file_t_size(file) + 1));   <===  l6
    for (; file != NULL; file = file->next) {
        if (i != -1 && !check_line(file->name))
            return NULL;
        if (my_strcmp(file->name, "##start\n") == 0)
            st++;
        if (my_strcmp(file->name, "##end\n") == 0)
            end++;
        res[++i] = file->name;
    }
    if (st != 1 || end != 1)
        return NULL;
    res[++i] = NULL;
    return (res);
}   <====    G2 ?

### Version

Yes

### What OS are you seeing the problem on?

Debian based

**Comment by Just1truc** [comment]
hi,

L5 and L6 are justified because you didn't launched abricot where it would be able to get typedef names

However, G2 are cringes.

I'll fixed them asap

**Comment by Just1truc** [comment]
Hi,

G2 has been fixed thanks to you. Thank you
The line nbr given wasn't the one with a problem

Ha ve a nice day
