### ISSUE TITLE
[BUG]: MAKEFILE NOT IN SNAKECASE

### ISSUE THREAD

**Issue by MathiDEV** [Just1truc/Abricot-Norminette#46]
### What happened?

```
‣ Bad files :
  [MAJOR] (O4) - Name not in snake case convention. (Makefile)
```

### Version

Yes

### What OS are you seeing the problem on?

Debian based

**Comment by Just1truc** [comment]
Hi,

Thanks for your report, this issue has been fixed

Have a nice day.
