### ISSUE TITLE
[BUG]: V1 - Enum without equal sign results in a V1 error

### ISSUE THREAD

**Issue by mvallenet** [Just1truc/Abricot-Norminette#47]
### What happened?

When I defined an enum without an equal sign, a V1 error appeared telling me that one of my macro should be in uppercase.

All my macros are in uppercase though.

```c
enum STEP_CONNECTION {
    USER,
    PASS,
    LOGGED
};
```

I decided to display the output of the content on which you detect if a character was in lowercase and inside was my structure definition which has nothing to do with the enum

The line of code which allows to get only the enum is not valid

```py
for macro in enums.replace("enum", "").split("{")[1].replace("}", "").split(","):
```

### Version

Yes

### What OS are you seeing the problem on?

Debian based

### Relevant output

```shell
‣ In File include/my_ftp.h
  [MAJOR] (V1) - Macros should be in Uppercases (include/my_ftp.h:30)
```

**Comment by Fyroeo** [comment]
fixed on #48
