### ISSUE TITLE
L4 Misplaced Curly Brackets on "do while;" unsupported

### ISSUE THREAD

**Issue by leodubosclard** [Just1truc/Abricot-Norminette#6]
# L4 Misplaced Curly Brackets

Bonjour,

J'ai le regret de vous informer que les [L4] Misplaced Curly Brackets ne sont malheureusement pas prisent en compte par votre norminette pour les boucles "do while;".

En effet, votre norminette me signale une L4 sur ma boucle alors que je suis parfaitement en droit et que ce type d'écriture est totalement autorisée au Coding style.

De plus, si vous n'êtes pas satifsait de mes simples phrases pour vous expliquer ce problème. Vous trouverez ci-joint, deux images de preuves.

Merci de mettre à jour votre norminette au plus vite.

Cordialement,

DUBOSCLARD Léo
1ère année (Promotion 2026)
Epitech Lyon
leo.dubosclard@epitech.eu

# Preuves
![image](https://user-images.githubusercontent.com/47077683/150963619-32c09fae-d75d-4a35-baf4-27e00a69746b.png)
![image](https://user-images.githubusercontent.com/47077683/150963646-9f3604df-2397-4bc8-9a50-a2d689890edb.png)

**Comment by Just1truc** [comment]
Hello,

Considering the issue you reported, i fixed the detection of this error.
You are welcome to report any error you discover so i can fix them in order to continuously improve this tool.

Best regards, Duc Justin.
