### ISSUE TITLE
Error on UBUNTU INSTALL

### ISSUE THREAD

**Issue by MathiDEV** [Just1truc/Abricot-Norminette#7]
# Bonjour,
il semblerait que lors que j’exécute `./abricot_install` ou `sh abricot_install`, l'installation se déroute convenablement cependant une erreur apparaît et je suppose qu'elle peut être problématique.
L'erreur est la suivante :
`install_abricot.sh: 32: [[: not found`

Le script d'installation marche parfaitement en remplaçant le shebang `#!/bin/sh` par `#!/bin/bash`

Mes spécifications techniques :
```
OS: Pop!_OS 21.10 x86_64 
Host: ZenBook UX534FAC_UX534FA 1.0 
Kernel: 5.15.8-76051508-generic 
Uptime: 1 day, 3 hours, 47 mins 
Packages: 2413 (dpkg), 15 (flatpak) 
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: GNOME 40.5 
WM: Mutter 
WM Theme: Adwaita 
Theme: Orchis-dark [GTK2/3] 
Icons: Tela-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-10210U (8) @ 4.200GHz 
GPU: Intel CometLake-U GT2 [UHD Graph 
Memory: 5995MiB / 7749MiB
Taille Caleçon: S
```

**Comment by Just1truc** [comment]
Hello,

First of all, thanks for reporting this issue. Thanks to that, this problem has been fixed.
Also, if you discover other issues, reporting them would be a great help.

Best regards, Duc Justin
